# Generated by Django 3.2.16 on 2022-10-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="jira_id",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
