# Generated by Django 3.2.16 on 2022-10-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_jira_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxTable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("topic", models.CharField(max_length=200)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("event_name", models.CharField(max_length=200)),
                ("version", models.SmallIntegerField()),
                ("sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "task_outbox_table",
                "ordering": ["created_at"],
            },
        ),
    ]
