POST http://localhost:8000/api/v1/token/

{
  "username": "admin",
  "password": "develop"
}

###

GET http://localhost:8002/api/v1/accounts/me/?include[]=transactions.*
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY1OTY0OTEyLCJpYXQiOjE2NjU5NjQwMTIsImp0aSI6IjlhMDI0ZTY1MjdjMDQxNjJhZmQzYjNmNTA5Y2UxYjZkIiwidXNlcl9pZCI6ImJjNWJkOWQ1LWQ4NGEtNDI2YS05MjI1LTIwZTllN2E4YjEzMiIsInJvbGUiOiJcdTA0MTBcdTA0MzRcdTA0M2NcdTA0MzhcdTA0M2RcdTA0MzhcdTA0NDFcdTA0NDJcdTA0NDBcdTA0MzBcdTA0NDJcdTA0M2VcdTA0NDAifQ.P8HnrPLNqPfImlybAQfTck0EcgFNRhngJPUZNY3FnG0

###

GET http://localhost:8002/api/v1/accounts/?include[]=user.*&include[]=transactions.*
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY1OTY0OTEyLCJpYXQiOjE2NjU5NjQwMTIsImp0aSI6IjlhMDI0ZTY1MjdjMDQxNjJhZmQzYjNmNTA5Y2UxYjZkIiwidXNlcl9pZCI6ImJjNWJkOWQ1LWQ4NGEtNDI2YS05MjI1LTIwZTllN2E4YjEzMiIsInJvbGUiOiJcdTA0MTBcdTA0MzRcdTA0M2NcdTA0MzhcdTA0M2RcdTA0MzhcdTA0NDFcdTA0NDJcdTA0NDBcdTA0MzBcdTA0NDJcdTA0M2VcdTA0NDAifQ.P8HnrPLNqPfImlybAQfTck0EcgFNRhngJPUZNY3FnG0

###

GET http://localhost:8002/api/v1/transactions/?filter{account.id}=5
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY1OTY0OTEyLCJpYXQiOjE2NjU5NjQwMTIsImp0aSI6IjlhMDI0ZTY1MjdjMDQxNjJhZmQzYjNmNTA5Y2UxYjZkIiwidXNlcl9pZCI6ImJjNWJkOWQ1LWQ4NGEtNDI2YS05MjI1LTIwZTllN2E4YjEzMiIsInJvbGUiOiJcdTA0MTBcdTA0MzRcdTA0M2NcdTA0MzhcdTA0M2RcdTA0MzhcdTA0NDFcdTA0NDJcdTA0NDBcdTA0MzBcdTA0NDJcdTA0M2VcdTA0NDAifQ.P8HnrPLNqPfImlybAQfTck0EcgFNRhngJPUZNY3FnG0

###

GET http://localhost:8002/api/v1/company-earn/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY1OTY0OTEyLCJpYXQiOjE2NjU5NjQwMTIsImp0aSI6IjlhMDI0ZTY1MjdjMDQxNjJhZmQzYjNmNTA5Y2UxYjZkIiwidXNlcl9pZCI6ImJjNWJkOWQ1LWQ4NGEtNDI2YS05MjI1LTIwZTllN2E4YjEzMiIsInJvbGUiOiJcdTA0MTBcdTA0MzRcdTA0M2NcdTA0MzhcdTA0M2RcdTA0MzhcdTA0NDFcdTA0NDJcdTA0NDBcdTA0MzBcdTA0NDJcdTA0M2VcdTA0NDAifQ.P8HnrPLNqPfImlybAQfTck0EcgFNRhngJPUZNY3FnG0
