# Generated by Django 3.2.16 on 2022-10-22 13:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0002_task_executor"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("type", models.CharField(choices=[("assign", "assign"), ("complete", "complete")], max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name="events", to="tasks.task"
                    ),
                ),
            ],
        ),
    ]
