POST http://localhost:8000/api/v1/token/

{
  "username": "admin",
  "password": "develop"
}

###

GET http://localhost:8001/api/v1/tasks/?include[]=executor
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY1MjI5NzkyLCJpYXQiOjE2NjUyMjg4OTIsImp0aSI6ImM2MDVjNDlmZGQ2YzRkN2ZiZjIxYTRmNTUyOTEwYWM4IiwidXNlcl9pZCI6ImJjNWJkOWQ1LWQ4NGEtNDI2YS05MjI1LTIwZTllN2E4YjEzMiIsInJvbGUiOiJcdTA0MTBcdTA0MzRcdTA0M2NcdTA0MzhcdTA0M2RcdTA0MzhcdTA0NDFcdTA0NDJcdTA0NDBcdTA0MzBcdTA0NDJcdTA0M2VcdTA0NDAifQ.7a4qf5OUswCN05njDTTmjg02DP_Lx-aLNNi309hrsUo

###

POST http://localhost:8001/api/v1/tasks/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY1MjcwMDA4LCJpYXQiOjE2NjUyNjkxMDgsImp0aSI6ImQ3N2FmZWY1ZWM5YjQ1NTdhYjdiNjVkYjRhZGQ2NGM2IiwidXNlcl9pZCI6ImJjNWJkOWQ1LWQ4NGEtNDI2YS05MjI1LTIwZTllN2E4YjEzMiIsInJvbGUiOiJcdTA0MTBcdTA0MzRcdTA0M2NcdTA0MzhcdTA0M2RcdTA0MzhcdTA0NDFcdTA0NDJcdTA0NDBcdTA0MzBcdTA0NDJcdTA0M2VcdTA0NDAifQ.r1BBsvAFh6JH-QV4wYMGvgdXSASU2Q86sjd-TNrLG1Y

{
  "title": "from api"
}

###

PATCH http://localhost:8001/api/v1/tasks/5/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY1MjcwMDA4LCJpYXQiOjE2NjUyNjkxMDgsImp0aSI6ImQ3N2FmZWY1ZWM5YjQ1NTdhYjdiNjVkYjRhZGQ2NGM2IiwidXNlcl9pZCI6ImJjNWJkOWQ1LWQ4NGEtNDI2YS05MjI1LTIwZTllN2E4YjEzMiIsInJvbGUiOiJcdTA0MTBcdTA0MzRcdTA0M2NcdTA0MzhcdTA0M2RcdTA0MzhcdTA0NDFcdTA0NDJcdTA0NDBcdTA0MzBcdTA0NDJcdTA0M2VcdTA0NDAifQ.r1BBsvAFh6JH-QV4wYMGvgdXSASU2Q86sjd-TNrLG1Y

{
  "title": "from api (patched)"
}

###

PATCH http://localhost:8001/api/v1/tasks/6/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY1MjcwMDA4LCJpYXQiOjE2NjUyNjkxMDgsImp0aSI6ImQ3N2FmZWY1ZWM5YjQ1NTdhYjdiNjVkYjRhZGQ2NGM2IiwidXNlcl9pZCI6ImJjNWJkOWQ1LWQ4NGEtNDI2YS05MjI1LTIwZTllN2E4YjEzMiIsInJvbGUiOiJcdTA0MTBcdTA0MzRcdTA0M2NcdTA0MzhcdTA0M2RcdTA0MzhcdTA0NDFcdTA0NDJcdTA0NDBcdTA0MzBcdTA0NDJcdTA0M2VcdTA0NDAifQ.r1BBsvAFh6JH-QV4wYMGvgdXSASU2Q86sjd-TNrLG1Y

{
  "status": "Завершена"
}

###

POST http://localhost:8001/api/v1/tasks/reassign/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY1MjcwMDA4LCJpYXQiOjE2NjUyNjkxMDgsImp0aSI6ImQ3N2FmZWY1ZWM5YjQ1NTdhYjdiNjVkYjRhZGQ2NGM2IiwidXNlcl9pZCI6ImJjNWJkOWQ1LWQ4NGEtNDI2YS05MjI1LTIwZTllN2E4YjEzMiIsInJvbGUiOiJcdTA0MTBcdTA0MzRcdTA0M2NcdTA0MzhcdTA0M2RcdTA0MzhcdTA0NDFcdTA0NDJcdTA0NDBcdTA0MzBcdTA0NDJcdTA0M2VcdTA0NDAifQ.r1BBsvAFh6JH-QV4wYMGvgdXSASU2Q86sjd-TNrLG1Y
