"""
Django settings for accounting project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import datetime as dt
import os
from distutils.util import strtobool
from pathlib import Path

import scheme_registry
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(strtobool(os.getenv("DEBUG", "no")))

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")


# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "rest_framework_simplejwt",
    "dynamic_rest",
    "drf_yasg",
    "django_filters",
    "kafka_consumer",
]

LOCAL_APPS = [
    "apps.users",
    "apps.tasks",
    "apps.accounts",
    "apps.api",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "accounting.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "accounting.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTH_USER_MODEL = "users.User"


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "EXCEPTION_HANDLER": "apps.api.exception_handler.exception_handler",
    "SEARCH_PARAM": "q",
    "ORDERING_PARAM": "o",
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
}

SIMPLE_JWT = {
    "AUTH_TOKEN_CLASSES": [
        "accounting.authentication.AccessToken",
    ],
    "ACCESS_TOKEN_LIFETIME": dt.timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": dt.timedelta(days=14),
    "AUTH_HEADER_TYPES": ("JWT",),
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,
    "USER_ID_FIELD": "public_id",
}

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "JWT": {"type": "apiKey", "name": "Authorization", "in": "header"},
    },
    "USE_SESSION_AUTH": False,
    "LOGIN_URL": "/admin/login/",
    "LOGOUT_URL": "/admin/logout/",
}

DYNAMIC_REST = {
    "ENABLE_LINKS": False,
    "ENABLE_BULK_PARTIAL_CREATION": False,
    "ENABLE_BULK_UPDATE": False,
    "ENABLE_PATCH_ALL": False,
    "MAX_PAGE_SIZE": None,
    "PAGE_QUERY_PARAM": "page",
    "PAGE_SIZE": None,
    "PAGE_SIZE_QUERY_PARAM": "per_page",
}

SCHEME_REGISTRY = scheme_registry.SchemeRegistry()

KAFKA_HOSTS = os.getenv("KAFKA_BOOTSTRAP_SERVERS")
KAFKA_CLIENT_ID = os.getenv("KAFKA_CLIENT_ID")
KAFKA_CONSUMER_TOPICS = {
    "user-stream": {
        "topic": "user-stream",  # no spaces allowed!
        "group": f"{KAFKA_CLIENT_ID}-user-stream",
        "client": KAFKA_CLIENT_ID,
        "subscribers": ["apps.users.consumers.UserConsumerV1"],
        "message_processor": "common-processor",  # lookup in KAFKA_CONSUMERS_MESSAGE_PROCESSORS
        "wait": 0,  # optional, indicates how many seconds Kafka will wait to fillup buffer, None or ommited means wait forever
        "max_number_of_messages_in_batch": 200,
        "consumer_options": {  # Overrides options used to create KafkaConsumer
            "auto_offset_reset": "earliest",
        },
    },
    "task-stream": {
        "topic": "task-stream",  # no spaces allowed!
        "group": f"{KAFKA_CLIENT_ID}-task-stream",
        "client": KAFKA_CLIENT_ID,
        "subscribers": ["apps.tasks.consumers.TaskConsumerV2"],
        "message_processor": "common-processor",  # lookup in KAFKA_CONSUMERS_MESSAGE_PROCESSORS
        "wait": 0,  # optional, indicates how many seconds Kafka will wait to fillup buffer, None or ommited means wait forever
        "max_number_of_messages_in_batch": 200,
        "consumer_options": {  # Overrides options used to create KafkaConsumer
            "auto_offset_reset": "earliest",
        },
    },
    "task-registered": {
        "topic": "task-registered",  # no spaces allowed!
        "group": f"{KAFKA_CLIENT_ID}-task-registered",
        "client": KAFKA_CLIENT_ID,
        "subscribers": ["apps.tasks.consumers.TaskConsumerV2"],
        "message_processor": "common-processor",  # lookup in KAFKA_CONSUMERS_MESSAGE_PROCESSORS
        "wait": 0,  # optional, indicates how many seconds Kafka will wait to fillup buffer, None or ommited means wait forever
        "max_number_of_messages_in_batch": 200,
        "consumer_options": {  # Overrides options used to create KafkaConsumer
            "auto_offset_reset": "earliest",
        },
    },
    "task-assigned": {
        "topic": "task-assigned",  # no spaces allowed!
        "group": f"{KAFKA_CLIENT_ID}-task-assigned",
        "client": KAFKA_CLIENT_ID,
        "subscribers": ["apps.tasks.consumers.TaskConsumerV1"],
        "message_processor": "common-processor",  # lookup in KAFKA_CONSUMERS_MESSAGE_PROCESSORS
        "wait": 0,  # optional, indicates how many seconds Kafka will wait to fillup buffer, None or ommited means wait forever
        "max_number_of_messages_in_batch": 200,
        "consumer_options": {  # Overrides options used to create KafkaConsumer
            "auto_offset_reset": "earliest",
        },
    },
    "task-completed": {
        "topic": "task-completed",  # no spaces allowed!
        "group": f"{KAFKA_CLIENT_ID}-task-completed",
        "client": KAFKA_CLIENT_ID,
        "subscribers": ["apps.tasks.consumers.TaskConsumerV1"],
        "message_processor": "common-processor",  # lookup in KAFKA_CONSUMERS_MESSAGE_PROCESSORS
        "wait": 0,  # optional, indicates how many seconds Kafka will wait to fillup buffer, None or ommited means wait forever
        "max_number_of_messages_in_batch": 200,
        "consumer_options": {  # Overrides options used to create KafkaConsumer
            "auto_offset_reset": "earliest",
        },
    },
}
KAFKA_CONSUMERS_MESSAGE_PROCESSORS = {
    "common-processor": {
        "class": "kafka_util.consumer.MessageProcessor",
    },
}
KAFKA_CONSUMER_SSL_SETTINGS = {
    "security_protocol": "PLAINTEXT",
}

AUTH_SERVER_VERIFY_ENDPOINT = os.getenv("AUTH_SERVER_VERIFY_ENDPOINT")
